services:
  bot:
    build: .
    container_name: bot_telegram
    restart: always
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "start"]
