version: "3.8"

services:
  bot:
    build: .
    container_name: bot_telegram
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "./src/aplicationBotTelegram.js"]
